name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["*"]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Apt packages
        run: sudo apt-get update

      - name: Setup | Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
          components: clippy, rustfmt

      - name: Setup | Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup | Just
        uses: extractions/setup-just@v3

      - name: Test | CI Pipeline
        run: just ci
